### ISSUE TITLE
Some issues on boolean type.

### ISSUE THREAD

**Issue by Ionizing** [ramonhagenaars/nptyping#21]
Thank you for your work on type hinting of numpy and I benefitted a lot.

In the previous version, which `Array` was still not removed, everything worked fine. But when I updated and found I couldn't deal with boolean type with it. Here is the MWE. I wonder if it is possible the maintainer could give some help ...

MWE:

```
Python 3.7.5 (default, Nov  1 2019, 02:16:23)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from nptyping import *
>>> NDArray[np.bool]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 68, in __call__
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 65, in _get_type_type
    return delegate(type_)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 131, in get_type_int
    int: DEFAULT_INT_BITS,
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 98, in _get_type_of_number
    .format(type(obj).__name__, cls))
TypeError: Unsupported type type for Int
......
SOME ERROR INFO HERE
......
>>> NDArray[bool]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 68, in __call__
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 65, in _get_type_type
    return delegate(type_)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 131, in get_type_int
    int: DEFAULT_INT_BITS,
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 98, in _get_type_of_number
    .format(type(obj).__name__, cls))
TypeError: Unsupported type type for Int
......
SOME ERROR INFO EHRE
```

My environment:
- macOS 10.15.1
- Python 3.7.5
- nptyping 1.1.0
- numpy 1.18.5

<details><summary>FULL ERROR LOG</summary>
<p>

```shell
Python 3.7.5 (default, Nov  1 2019, 02:16:23)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from nptyping import *
>>> NDArray[np.bool]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 68, in __call__
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 65, in _get_type_type
    return delegate(type_)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 131, in get_type_int
    int: DEFAULT_INT_BITS,
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 98, in _get_type_of_number
    .format(type(obj).__name__, cls))
TypeError: Unsupported type type for Int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 68, in __call__
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nptyping/types/_ndarray_meta.py", line 134, in _only_type
    cls._type = Any if item is Any else get_type(item)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 45, in get_type
    return function(obj)
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 71, in __call__
    .format(args[0], err.args[0]))
TypeError: Unable to call function for '<class 'bool'>': Unsupported type type for Int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_subscriptable_type.py", line 37, in __getitem__
    result._after_subscription(item)
  File "/usr/local/lib/python3.7/site-packages/nptyping/types/_ndarray_meta.py", line 121, in _after_subscription
    method(item)
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 71, in __call__
    .format(args[0], err.args[0]))
TypeError: Unable to call function for '<class 'bool'>': Unable to call function for '<class 'bool'>': Unsupported type type for Int
>>> NDArray[bool]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 68, in __call__
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 65, in _get_type_type
    return delegate(type_)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 131, in get_type_int
    int: DEFAULT_INT_BITS,
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 98, in _get_type_of_number
    .format(type(obj).__name__, cls))
TypeError: Unsupported type type for Int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 68, in __call__
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nptyping/types/_ndarray_meta.py", line 134, in _only_type
    cls._type = Any if item is Any else get_type(item)
  File "/usr/local/lib/python3.7/site-packages/nptyping/functions/_get_type.py", line 45, in get_type
    return function(obj)
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 71, in __call__
    .format(args[0], err.args[0]))
TypeError: Unable to call function for '<class 'bool'>': Unsupported type type for Int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_subscriptable_type.py", line 37, in __getitem__
    result._after_subscription(item)
  File "/usr/local/lib/python3.7/site-packages/nptyping/types/_ndarray_meta.py", line 121, in _after_subscription
    method(item)
  File "/usr/local/lib/python3.7/site-packages/typish/classes/_cls_function.py", line 71, in __call__
    .format(args[0], err.args[0]))
TypeError: Unable to call function for '<class 'bool'>': Unable to call function for '<class 'bool'>': Unsupported type type for Int
```

</p>
</details>

**Comment by ramonhagenaars** [comment]
Hi @Ionizing 

Glad to hear that you find nptyping useful. Release 1.2.0 now supports a `Bool` type. Please check if it works for you and let me know otherwise.

**Comment by Ionizing** [comment]
I tried and everything works fine now! Thank you!
